"""ma première migration pour créer ma table tache

Revision ID: 25604adf9043
Revises: 
Create Date: 2026-02-25 13:08:13.010929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25604adf9043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_mise_a_jour', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tache_id'), 'Tache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tache_id'), table_name='Tache')
    op.drop_table('Tache')
    # ### end Alembic commands ###
