"""Mise en place de la colonne description

Revision ID: abe7f4376167
Revises: 25604adf9043
Create Date: 2026-02-27 10:01:45.864324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe7f4376167'
down_revision: Union[str, Sequence[str], None] = '25604adf9043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tache', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tache', 'description')
    # ### end Alembic commands ###
